# Generated by Django 6.0.4 on 2026-08-26 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('string_instruments', 'Струнні'), ('wind_instruments', 'Духові'), ('percussion_instruments', 'Ударні'), ('keyboards', 'Клавішні'), ('electromusical', 'Електромузичні')], default='string_instruments', max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('serial_number', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('product_condition', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('complectation', models.TextField()),
                ('instrument_image', models.ImageField(upload_to='instruments_images/')),
                ('price', models.IntegerField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to='core_profile.account')),
            ],
        ),
    ]
