# Generated by Django 6.0.4 on 2026-09-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_menu', '0001_initial'),
        ('core_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('cash_when_delivered', 'Готівка при отриманні'), ('online_payment', 'Онлайн оплата')], default='cash_when_delivered', max_length=45)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('processing', 'В обробці'), ('shipped', 'Відправлений'), ('completed', 'Виконаний'), ('cancelled', 'Скасований')], default='new', max_length=20)),
                ('delivery_adress', models.TextField()),
                ('total_price', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core_profile.account')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('price', models.IntegerField()),
                ('is_shipped', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_menu.instrument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_order.order')),
            ],
        ),
    ]
